title: Diyanah Nadzree # your name (or website title) here
logo: "/images/profilepic.png?raw=true" # your photo (or logo) here
description:
  > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Hello world! 
  <br>
  I'm a multi-talented web and mobile developer with various skillsets, and am known to perform in deadline-driven environments.
  <br><br>
  Front-end Web Developer (VueJS) | Mobile Developer (React Native) | UI/UX Designer (Figma / Adobe Photoshop) | Video Editor (Adobe Premiere Pro) | Production Designer | Bioinformatics Student (Python / GAML)
  <br><br>
  Bachelor in Bioinformatics (Hons.)
  <br><br>
  <hr>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
