title: Diyanah Nadzree # your name (or website title) here
logo: "/images/profile_pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Hello world! My name is Diyanah Nadzree, and I'm new in the web development industry. 
  <br><br>
  I'm a hard-working web developer with the ability to solve problems with creative solutions in the least amount of time. 
  <br><br>
  I have created a couple of projects using Vue.JS and also designed projects on Figma.
  <br><br>
  I still have a long way to go, but I'm highly-motivated and passionate at what I'm doing, and am eager to learn more to improve myself. I'm always up for new experiences and adventures that I can learn from.
  <br><br>
  <a href="https://www.linkedin.com/in/diyanah-nadzree/">View My LinkedIn Profile</a> 
  <br>
  
  ---
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
