title: Diyanah Nadzree # your name (or website title) here
logo: "/images/profile_pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Hello world! My name is Diyanah Nadzree, and I am new in the world of web development. 
  <br><br>
  I am a hard-working web developer with the ability to solve problems with creative solutions in the least amount of time. 
  <br>
  I have created a couple of projects using Vue.JS and also designed projects on Figma.
  <br>
  I still have a long way to go, but I am passionate at what I am doing, and I am eager to learn more to improve myself. I am always up for new experiences and adventures I can learn from.
  <br><br>
  <a href="https://www.linkedin.com/in/diyanah-nadzree/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
